/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    // Override colors so default Tailwind color palette is removed
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: 'var(--surface)',
      bg: 'var(--bg)',
      surface: 'var(--surface)',
      'surface-sunken': 'var(--surface-sunken)',
      border: 'var(--border)',
      'border-strong': 'var(--border-strong)',
      'text-primary': 'var(--text-primary)',
      'text-secondary': 'var(--text-secondary)',
      'text-tertiary': 'var(--text-tertiary)',
      'text-on-brand': 'var(--text-on-brand)',
      brand: 'var(--brand)',
      'brand-hover': 'var(--brand-hover)',
      'brand-soft': 'var(--brand-soft)',
      'brand-soft-border': 'var(--brand-soft-border)',
      success: 'var(--success)',
      'success-soft': 'var(--success-soft)',
      warning: 'var(--warning)',
      'warning-soft': 'var(--warning-soft)',
      danger: 'var(--danger)',
      'danger-soft': 'var(--danger-soft)',
      info: 'var(--info)',
      'info-soft': 'var(--info-soft)',
    },
    extend: {
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
    },
  },
  plugins: [],
}
